name: Build and Deploy SQL Database Schema

on:
  workflow_dispatch:

env:
  SQL_SCRIPT_PATH: 'sql/Delete_ProductsDb.sql'  # Path to SQL script here

jobs:
  deploy-database:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Azure Login action for authentication
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy SQL Database Schema
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.DB_CONNECTION_STRING }}
          path: ${{ env.SQL_SCRIPT_PATH }}
