name: Build and Deploy SQL Database Schema

on:
  workflow_dispatch:

env:
  SQL_SCRIPT_PATH: 'sql/ProductsDb.sql'  # Path to SQL script here

jobs:
  deploy-database:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Azure Login action for authentication
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Deploy SQL Database Schema
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.DB_CONNECTION_STRING }}
          path: ${{ env.SQL_SCRIPT_PATH }}
