name: Deploy ARM Template

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: 'test-env'  # Set your target resource group name
  TEMPLATE_FILE: 'templates/azuredeploy.endpoint.json'  # Path to ARM template JSON file
  Deployment_Name: 'azuredeploy.endpoint'

jobs:
  deploy-arm-template:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        id: deploy-arm
        run: |
          az deployment group create --resource-group ${{ env.RESOURCE_GROUP }} --template-file ${{ env.TEMPLATE_FILE }}
        
      - name: Check Deployment Status
        run: |
          $deploymentStatus = az deployment group show --name $env:Deployment_Name --resource-group $env:RESOURCE_GROUP --query properties.provisioningState -o tsv
          Write-Host "Deployment Status: $deploymentStatus"
