name: Build, Deploy, and Use SQL Database Schema

on:
  workflow_dispatch:

env:
  SQL_SCRIPT_PATH: 'sql/ProductsDb.sql'  # Path to SQL script here
  RESOURCE_GROUP: 'test-env'  # Set your default resource group here

jobs:
  build-deploy-use-database:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get SQL Server Name
        id: get-sql-server-name
        run: |
          $SQL_SERVER_NAME = & az graph query -q "resources | where type == 'microsoft.sql/servers' | where resourceGroup == '$env:RESOURCE_GROUP' | project name" --output tsv
          Write-Host "SQL_SERVER_NAME=$SQL_SERVER_NAME"
          echo "SQL_SERVER_NAME=$SQL_SERVER_NAME" >> $env:GITHUB_ENV

      - name: Get Database Name
        id: get-database-name
        run: |
          $DATABASE_NAME = & az graph query -q "resources | where type == 'microsoft.sql/servers/databases' | where resourceGroup == '$env:RESOURCE_GROUP' | project name" --output tsv
          Write-Host "DATABASE_NAME=$DATABASE_NAME"
          echo "DATABASE_NAME=$DATABASE_NAME" >> $env:GITHUB_ENV

      - name: Retrieve SQL Username and Password
        id: get-credentials
        run: |
          $SQL_USERNAME = $env:SQL_USERNAME
          $SQL_PASSWORD = $env:SQL_PASSWORD
          Write-Host "SQL_USERNAME=$SQL_USERNAME"
          Write-Host "SQL_PASSWORD=$SQL_PASSWORD"
          echo "SQL_USERNAME=$SQL_USERNAME" >> $env:GITHUB_ENV
          echo "SQL_PASSWORD=$SQL_PASSWORD" >> $env:GITHUB_ENV

      - name: Get SQL Connection String
        id: get-connection-string
        run: |
          $CONNECTION_STRING = & az sql db show-connection-string --name "$env:DATABASE_NAME" --server "$env:SQL_SERVER_NAME" --type ado.net --output tsv
          Write-Host "CONNECTION_STRING=$CONNECTION_STRING"
          echo "CONNECTION_STRING=$CONNECTION_STRING" >> $env:GITHUB_ENV

      - name: Modify Connection String with Correct Values
        run: |
          (Get-Content $env:GITHUB_ENV) -replace '<username>', $env:SQL_USERNAME -replace '<password>', $env:SQL_PASSWORD -replace '<server>', "$env:SQL_SERVER_NAME.database.windows.net" -replace '<database>', $env:DATABASE_NAME | Set-Content $env:GITHUB_ENV

      - name: Deploy SQL Database Schema
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ env.CONNECTION_STRING }}
          path: ${{ env.SQL_SCRIPT_PATH }}

      - name: Azure Logout
        run: az logout

      # Add more steps here as needed for your application, such as running tests, deploying your app, etc.
